MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: "ckpt" # root of pretrain path
  PRETRAIN_PATH: "ckpt" # root of pretrain path
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'no'
  NAME: 'part_attention_vit'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  MMPOSE_CONFIG: '../../mmpose/td-hm_hrnet-w48_8xb32-210e_coco-256x192.py'
  MMPOSE_CKPT: '../../mmpose/td-hm_hrnet-w48_8xb32-210e_coco-256x192-0e67c616_20220913.pth'

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]
  REA:
    ENABLED: False
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  LGT: # Local Grayscale Transfomation
    DO_LGT: True
    PROB: 0.5

DATASETS:
  TRAIN: ('Market1501',) # CUHK03, Market1501, MSMT17
  TEST: ("Market1501",)
  ROOT_DIR: ('../../data') # root of datasets
  ROOT_DIR: ('../../data') # root of datasets

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 60
  BASE_LR: 0.001 # 0.0004 for msmt
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 60
  EVAL_PERIOD: 1
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  SEED: 1234

TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: 'log/market_both/part_attention_vit_60.pth' # pretrained file path
  NECK_FEAT: 'before'
  FEAT_NORM: True

LOG_ROOT: 'log/' # root of log file
LOG_ROOT: 'log/' # root of log file
TB_LOG_ROOT: 'tb_log/'
LOG_NAME: 'market_both/'

INFERABILITY:
  TRIPLET: True
  ALPHA: 0.5
  POS: False
  DISCRETE: False

